### ISSUE TITLE
How to seed rank to db rows

### ISSUE THREAD

**Issue by isaac-manubag** [alexcrawford/lexorank-php#1]
Hey man, I'm trying out your package and wondering how I could use this to seed the rank using `$rank = (new Rank($prev, $next))->get();` on my current db rows.

I have something like this on my code
```
foreach ($ticketArray as $order => $ticket) {
    if ($order == 0) {
        $rank = (new Rank('', ''))->get();
    } else {
        $prevRank = $ticketArray[$order - 1]->rank;
        $rank = (new Rank("$prevRank", ""))->get();
    }

    $ticket->rank = $rank;
    $ticket->save();
}
```

the first few rows looks like this
```
U
g
U
g
p
u
w
x
y
yU
yg
yp
yu
yw
yx
yy
yyU
yyg
yyp
yyu
yyw
yyx
yyy
yyyU
yyyg
yyyp
```

but I have almost 500 rows and the generated ranks on the latter rows looks like these
```
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyU 
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyg 
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyp 
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyu 
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyw 
```

Which makes me think that the approach I'm doing on seeding rank is not right, what do you suggest?

**Comment by alexcrawford** [comment]
Hey Isaac - sorry I missed this.

For seeding/balancing, I start somewhere in the middle of the range and simply increment by one on each loop.

```php
$rank = 'gggggggggg';

foreach ($ticketArray as $ticket) {
    $ticket->rank = ++$rank;
    $ticket->save();
}
```
