### ISSUE TITLE
Proposal: MIT license

### ISSUE THREAD

**Issue by dereuromark** [alexcrawford/lexorank-php#5]
I initially wanted to https://github.com/ziadoz/awesome-php/pull/1169

But then I saw the license.
With this many companies or people will be held off using this library.

Would it be possible to use the default/standard FOSS license MIT?
This way, it would sure be better fit for people wanting to use this, including me/us.

Thank you!

**Comment by alexcrawford** [comment]
Sure, I’m not particularly attached to any specific licence.

**Comment by dereuromark** [comment]
The original one was even that it seems: https://github.com/xissy/lexorank

**Comment by alexcrawford** [comment]
This has been updated:
https://github.com/alexcrawford/lexorank-php/releases/tag/1.0.2
