### ISSUE TITLE
Generated Rank uses problematic signs

### ISSUE THREAD

**Issue by codegm** [alexcrawford/lexorank-php#8]
I have signs in my ranking string that makes trouble in the sorting.

` : ; < = > ? @ ^ [ \ ] _ - ` `

Is it intended that these signs are used?

After closer look it started in December 2022. Maybe it comes with a switch in php version? Currently php8.2. Or with the 2.0.0 update of laxorank-php?

To reproduce, start with:
`$next = Rank::forEmptySequence()->get() // U`

then:

`Rank::before(Rank::fromString($next))->get()`

Using the new generated value always for the next step, to generate the Rank before. The problematic signs comes after a couple of loops.

With Rank::after() it is the same.

**Comment by codegm** [comment]
It comes with the update to 2.0.0.

It is an symfony application and the sorting is done by fetching from the database with doctrine orm and `->addOrderBy('p.sort', 'DESC')`

It is even a problem that 'b' is sorted after/before 'B'...

**Comment by guidobonuzzi** [comment]
I think your problem is due to a case insensitive DB column.

When using MySQL, I usually set the column charset to `ascii` and collate to `ascii_bin`.

**Comment by codegm** [comment]
Yes indeed, changing the column collate to `utf8mb4_bin` does the sorting right. Thank you!

Maybe a note would be appropriate when changing the major version that more characters are now used.

**Comment by guidobonuzzi** [comment]
The 2.0.0 release did not change the character set and the sorting depends only on the database settings.

The new version just has an improved algorithm.
